name: CI

permissions:
  contents: read
  pull-requests: write

on:
  push:
    branches:
      - main
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: install dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Audit
        run: bun audit

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: install dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Build
        run: bun run build

  check-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Check Types
        run: bun check-types

  commitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-depth: 0

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Validate current commit (last commit) with commitlint
        if: github.event_name == 'push'
        run: bun commitlint --last --verbose

      - name: Validate PR commits with commitlint
        if: github.event_name == 'pull_request'
        run: >
          bun commitlint
          --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }}
          --to ${{ github.event.pull_request.head.sha }}
          --verbose

  editorconfig:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Run EditorConfig Checker
        run: bun editorconfig-checker

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Lint
        run: bun lint

  spell-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Check Spelling
        run: bun cspell .

  syncpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Run syncpack
        run: bun syncpack lint

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Test
        run: bun run test run

  validate-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Install Dependencies
        uses: ./.github/workflows/actions/install-dependencies

      - name: Run validate-branch-name
        run: bun validate-branch-name
